on:
  push:
    paths: "dl_action.yaml"
  workflow_dispatch:

jobs:
  rvdat-dl:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # VDAT_EXE: "D:\\a\\rvdat\\rvdat\\vdat.exe"
 # /Users/runner/work/rvdat/rvdat/vdat = mac /home/runner/work/rvdat/rvdat

    steps:
      - uses: actions/checkout@v4

      - name: VDAT location on Windows
        if: runner.os == 'Windows'
        run: |
          echo "VDAT_EXE=D:\\a\\rvdat\\rvdat\\vdat.exe" >> $env:GITHUB_ENV

      - name: VDAT location on Linux
        if: runner.os == 'Linux'
        run: |
          echo "VDAT_EXE=/home/runner/work/rvdat/rvdat/vdat.exe" >> $GITHUB_ENV

      - name: VDAT location on macOS
        if: runner.os == 'macOS'
        run: |
          echo "VDAT_EXE=/Users/runner/work/rvdat/rvdat/vdat.exe" >> $GITHUB_ENV

#      - uses: r-lib/actions/setup-r@v2
#        with:
#          use-public-rspm: true

#      - uses: r-lib/actions/setup-r-dependencies@v2
#        with:
#          packages:
#            any::testthat
#            local::.

      - name: Pull vdat.exe
        env:
          GL_PAT: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl -o vdat.exe --request GET --header "PRIVATE-TOKEN: $env:GL_PAT" "https://gitlab.oceantrack.org/api/v4/projects/otndc%2Fvdat%2Dworking%2Dgroup/repository/files/releases%2Fvdat-7.0.0-20231107%2FWindows-x86_64%2Fvdat%2Eexe/raw?ref=master"

      - name: Test vdat
        shell: cmd
        run: |
          vdat.exe --help

#       - name: Run a test
      #   run: |
      #     Rscript -e "testthat::test_file('tests/testthat/test-vdat_call.R', package = 'rvdat')"


