on:
  push:
    branches: ci-windows
  workflow_dispatch:

jobs:
  rvdat-dl:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITLAB_PAT: ${{ secrets.GITLAB_TOKEN }}
      VDAT_EXE: "D:\\a\\rvdat\\rvdat\\vdat.exe"
 # /Users/runner/work/rvdat/rvdat/vdat = mac /home/runner/work/rvdat/rvdat

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            local::.

      - name: Pull vdat.exe
        run: |
          curl -o vdat.exe --request GET --header $env:GITLAB_PAT "https://gitlab.oceantrack.org/api/v4/projects/otndc%2Fvdat-working-group/repository/files/releases%2Fvdat-7.0.0-20231107%2FWindows-x86_64%2Fvdat%2Eexe/raw?ref=master"

      - name: Test vdat
        shell: cmd
        run: |
          vdat.exe --help

      - name: List vdat
        run: |
          Rscript -e "Sys.getenv('VDAT_EXE')"

      - name: Call vdat
        run: |
          Rscript -e "rvdat::vdat_call()"

